language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t emsikes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run emsikes/react-test npm test -- --coverage

after_success: 
  - docker build -t emsikes/multi-client ./client
  - docker build -t emsikes/multi-nginx ./nginx
  - docker build -t emsikes/multi-server ./server
  - docker build -t emsikes/multi-worker ./worker



script:
  - docker run -e CI=true USERNAME/react-test npm test